# Generated by Django 3.2.9 on 2021-11-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Competences',
                'verbose_name_plural': 'Competences',
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=25)),
                ('whatsapp', models.CharField(max_length=25)),
                ('telegram', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Experts',
                'verbose_name_plural': 'Experts',
            },
        ),
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tarifs',
                'verbose_name_plural': 'Tarifs',
            },
        ),
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('competences', models.ManyToManyField(to='services.Competences')),
            ],
            options={
                'verbose_name': 'Stacks',
                'verbose_name_plural': 'Stacks',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('experts', models.ManyToManyField(to='services.Experts')),
                ('tarifs', models.ManyToManyField(to='services.Tarifs')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='experts',
            name='satcks',
            field=models.ManyToManyField(to='services.Stacks'),
        ),
    ]
