# Generated by Django 3.2.9 on 2021-11-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifs',
            name='name',
            field=models.CharField(default=models.IntegerField(default=1), max_length=25),
        ),
    ]
