# Generated by Django 3.2.9 on 2021-11-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_tarifs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='favoris',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarifs',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tarifs',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
