# Generated by Django 3.2.9 on 2021-11-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211119_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='note',
            field=models.IntegerField(default=2.5),
        ),
    ]
