# Generated by Django 3.2.9 on 2021-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_satcks_experts_stacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
