# Generated by Django 3.2.9 on 2021-11-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_services_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='services',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
