# Generated by Django 3.2.9 on 2021-11-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20211123_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
