# Generated by Django 3.2.9 on 2021-11-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('number', models.IntegerField(default=1)),
                ('price', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ManyToManyField(to='store.Images')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produit',
            },
        ),
    ]
