# Generated by Django 3.2.9 on 2021-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Produit', 'verbose_name_plural': 'Produit'},
        ),
        migrations.AddField(
            model_name='produit',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
