# Generated by Django 3.2.9 on 2021-11-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='Packitems',
        ),
        migrations.AddField(
            model_name='premium',
            name='Packitems',
            field=models.ManyToManyField(to='home.Pack'),
        ),
    ]
