# Generated by Django 3.2.9 on 2021-11-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211119_0356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pack',
            new_name='Packs',
        ),
        migrations.AlterModelOptions(
            name='packs',
            options={'verbose_name': 'Packs', 'verbose_name_plural': 'Packs'},
        ),
        migrations.RemoveField(
            model_name='premium',
            name='Packitems',
        ),
        migrations.AddField(
            model_name='premium',
            name='packs',
            field=models.ManyToManyField(to='home.Packs'),
        ),
    ]
